spring.application.name=service-registry
server.port=8761

# Désactiver l'auto-enregistrement d'Eureka sur lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Interface de la dashboard Eureka
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
