# ==============================================
# IDENTITÃ‰ DU SERVICE
# ==============================================
spring.application.name=account-service
# Port sur lequel ce service va Ã©couter les requÃªtes
server.port=8082

# ==============================================
# BASE DE DONNÃ‰ES POSTGRESQL
# ==============================================
# URL de connexion : jdbc:postgresql://[hÃ´te]:[port]/[nom_base]
# En local : localhost | En Docker : db-accounts (nom du container)
spring.datasource.url=jdbc:mysql://db-accounts:3306/accounts_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================
# JPA / HIBERNATE (ORM)
# ==============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================================
# KAFKA - COMMUNICATION ASYNCHRONE
# ==============================================
# Adresse du broker Kafka
spring.kafka.bootstrap-servers=kafka:9092
# Serializer : convertit les objets Java en JSON pour Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==============================================
# SWAGGER / OPENAPI - DOCUMENTATION AUTO
# ==============================================
# URL d'accÃ¨s Ã  la doc : http://localhost:8082/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ==============================================
# JWT - SÃ‰CURITÃ‰
# ==============================================
# ClÃ© secrÃ¨te pour vÃ©rifier les tokens JWT (doit Ãªtre la mÃªme dans tous les services)
jwt.secret=QmFucXVlUGxhdGZvcm1lU2VjcmV0S2V5Rm9ySldUVmFsaWRhdGlvbjIwMjZZYW91bmRlVW5pdmVyc2l0eQ==
jwt.expiration=86400000

# ==============================================
# LOGS
# ==============================================
logging.level.com.banque.account=DEBUG
logging.level.org.springframework.kafka=INFO

