# ==============================================
# IDENTITÉ DU SERVICE
# ==============================================
spring.application.name=account-service
# Port sur lequel ce service va écouter les requêtes
server.port=8082

# ==============================================
# BASE DE DONNÉES POSTGRESQL
# ==============================================
# URL de connexion : jdbc:postgresql://[hôte]:[port]/[nom_base]
# En local : localhost | En Docker : db-accounts (nom du container)
spring.datasource.url=jdbc:postgresql://db-accounts:5432/accounts_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================
# JPA / HIBERNATE (ORM)
# ==============================================
# update = crée les tables automatiquement si elles n'existent pas
# IMPORTANT : en production, utiliser "validate" au lieu de "update"
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL dans les logs (utile pour déboguer)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================================
# KAFKA - COMMUNICATION ASYNCHRONE
# ==============================================
# Adresse du broker Kafka
spring.kafka.bootstrap-servers=kafka:9092
# Serializer : convertit les objets Java en JSON pour Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==============================================
# SWAGGER / OPENAPI - DOCUMENTATION AUTO
# ==============================================
# URL d'accès à la doc : http://localhost:8082/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ==============================================
# JWT - SÉCURITÉ
# ==============================================
# Clé secrète pour vérifier les tokens JWT (doit être la même dans tous les services)
jwt.secret=BanquePlatformeSecretKeyForJWTValidation2026YaoundeUniversity
jwt.expiration=86400000

# ==============================================
# LOGS
# ==============================================
logging.level.com.banque.account=DEBUG
logging.level.org.springframework.kafka=INFO
